### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by fgksgf** [chenjiandongx/soksaccounts#2]
HTTPConnectionPool(host='xyz.ishadow.online', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000001816C45F358>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
>>  Generate gui-config.json successful

修改后的json文件内容：
{
"configs" : [
  {
"server" : "",
"server_port" : 8388,
"password" : "",
"method" : "aes-256-cfb",
"remarks" : ""}

],
"strategy" : "com.shadowsocks.strategy.ha",
"index" : -1,
"global" : false,
"enabled" : true,
"shareOverLan" : false,
"isDefault" : false,
"localPort" : 1080,
"pacUrl" : null,
"useOnlinePac" : false}

**Comment by chenjiandongx** [comment]
好久没试过了，可能网站失效了吧

**Comment by fgksgf** [comment]
好的，谢谢
